### PR TITLE
[YUNIKORN-1794] Define new messages in SI to support init per object

### PR DESCRIPTION
**Pull request by craigcondit**
### What is this PR for?
- Added `allocations` field to `AllocationRequest` to allow adding / updating allocations
- Added `CREATE_DRAIN` action to `NodeInfo` to allow creating node as initially unschedulable

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [x] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1794

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — CHANGES_REQUESTED** [review]
For consistency we should update the comment for CREATE to show that the node is created as schedulable. That is missing at the moment and lines up with the comment in DRAIN_TO_SCHEDULE about needing to handle an error coming back

**Comment by craigcondit** [comment]
Updated comment on CREATE.

**Review by wilfred-s — APPROVED** [review]
LGTM

**Review by pbacsko — APPROVED** [review]
+1 (after rebasing)

**Comment by craigcondit** [comment]
Rebased on master (no other changes).

**Pull request closed without merging**
